### ISSUE TITLE
Error message is missing

### ISSUE THREAD

**Issue by highsource** [highsource/jsonix-schema-compiler#26]
This is not helpful:
```
Exception in thread "main" java.lang.NullPointerException: The validated object is null
        at org.apache.commons.lang3.Validate.notNull(Validate.java:222)
        at org.apache.commons.lang3.Validate.notNull(Validate.java:203)
        at org.hisrc.jsonix.configuration.ModulesConfiguration.buildMappings(ModulesConfiguration.java:304)
        at org.hisrc.jsonix.configuration.ModulesConfiguration.buildModules(ModulesConfiguration.java:276)
        at org.hisrc.jsonix.configuration.ModulesConfiguration.build(ModulesConfiguration.java:97)
        at org.hisrc.jsonix.execution.JsonixInvoker.execute(JsonixInvoker.java:40)
        at org.hisrc.jsonix.JsonixMain.execute(JsonixMain.java:107)
        at org.hisrc.jsonix.JsonixMain.main(JsonixMain.java:76)
```

**Comment by paul-p** [comment]
I got the same error.

**Comment by highsource** [comment]
@paul-p 

Hi Paul,

yes, these are blockers. They mean two things map onto the same property name. This is a naming collision which needs to be resolved.

This issue here is only about `The validated object is null` not being vry helpful. This won't solve your issue.

You're obviously compiling GML 3.2.1. By the way I've got it compiled here:

https://github.com/highsource/ogc-schemas/tree/master/gml/3.2.1

Mappings are here:

https://github.com/highsource/ogc-schemas/blob/master/scripts/lib/GML_3_2_1.js

Maybe you could just use those?

If you want to compile on your own, you'll have to use a binding file to resolve naming collision. See this one, for instance:

https://github.com/highsource/ogc-schemas/blob/master/gml/3.2.1/src/main/resources/gml-v_3_2_1.xjb

Hope this helps

Best wishes,
Alexey

**Comment by highsource** [comment]
@paul-p 

ps. And XLink is here:

https://github.com/highsource/w3c-schemas/blob/master/scripts/lib/XLink_1_0.js

And that's the binding:

https://github.com/highsource/w3c-schemas/blob/master/xlink/1999/src/main/resources/xlink-v_1_0.xjb
