### ISSUE TITLE
Null Pointer Exception in MultiplicityCounterNG

### ISSUE THREAD

**Issue by rsperlazza** [highsource/jsonix-schema-compiler#62]
Using this xsd:
http://www.omg.org/spec/ReqIF/20110401/reqif.xsd

I get the following Null Pointer Exception:

Exception in thread "main" java.lang.NullPointerException
 at org.hisrc.jsonix.xml.xsom.MultiplicityCounterNG.particle(MultiplicityCounterNG.java:27)
        at org.hisrc.jsonix.xml.xsom.MultiplicityCounterNG.modelGroup(MultiplicityCounterNG.java:52)
        at org.hisrc.jsonix.xml.xsom.MultiplicityCounterNG.modelGroupDecl(MultiplicityCounterNG.java:43)
        at org.hisrc.jsonix.xml.xsom.MultiplicityCounterNG.modelGroupDecl(MultiplicityCounterNG.java:16)
        at com.sun.xml.xsom.impl.ModelGroupDeclImpl.apply(ModelGroupDeclImpl.java:89)
        at org.hisrc.jsonix.xml.xsom.MultiplicityCounterNG.particle(MultiplicityCounterNG.java:24)
        at org.hisrc.jsonix.xml.xsom.MultiplicityCounterNG.modelGroup(MultiplicityCounterNG.java:52)
        at org.hisrc.jsonix.xml.xsom.MultiplicityCounterNG.modelGroupDecl(MultiplicityCounterNG.java:43)
        at org.hisrc.jsonix.xml.xsom.MultiplicityCounterNG.modelGroupDecl(MultiplicityCounterNG.java:16)
        at com.sun.xml.xsom.impl.ModelGroupDeclImpl.apply(ModelGroupDeclImpl.java:89)
        at org.hisrc.jsonix.xml.xsom.ParticleMultiplicityCounter.particle(ParticleMultiplicityCounter.java:26)
        at org.hisrc.jsonix.xml.xsom.ParticleMultiplicityCounter.particle(ParticleMultiplicityCounter.java:12)
        at com.sun.xml.xsom.impl.ParticleImpl.apply(ParticleImpl.java:111)
        at org.hisrc.xml.xsom.XSFunctionApplier.apply(XSFunctionApplier.java:26)
        at org.hisrc.jsonix.compilation.mapping.PropertyInfoVisitor.createPropertyInfoOptions(PropertyInfoVisitor.java:59)
        at org.hisrc.jsonix.compilation.mapping.PropertyInfoVisitor.visitElementRefsPropertyInfo(PropertyInfoVisitor.java:254)
        at org.hisrc.jsonix.compilation.mapping.PropertyInfoVisitor.visitElementRefsPropertyInfo(PropertyInfoVisitor.java:38)
        at org.jvnet.jaxb2_commons.xml.bind.model.concrete.CMElementRefsPropertyInfo.acceptPropertyInfoVisitor(CMElementRefsPropertyInfo.java:68)
        at org.hisrc.jsonix.compilation.mapping.MappingCompiler.compilePropertyInfos(MappingCompiler.java:262)
        at org.hisrc.jsonix.compilation.mapping.MappingCompiler.compileClassInfo(MappingCompiler.java:232)
        at org.hisrc.jsonix.compilation.mapping.MappingCompiler.compileClassInfos(MappingCompiler.java:182)
        at org.hisrc.jsonix.compilation.mapping.MappingCompiler.compile(MappingCompiler.java:155)
        at org.hisrc.jsonix.compilation.mapping.ModuleCompiler.compile(ModuleCompiler.java:54)
        at org.hisrc.jsonix.compilation.mapping.ModulesCompiler.compile(ModulesCompiler.java:29)
        at org.hisrc.jsonix.execution.JsonixInvoker.execute(JsonixInvoker.java:64)
        at org.hisrc.jsonix.JsonixMain.execute(JsonixMain.java:110)
        at org.hisrc.jsonix.JsonixMain.main(JsonixMain.java:77)

Using a modified XSD that works in JAXB I still get the same exception:
http://pastebin.com/G4reNMBu

**Comment by highsource** [comment]
What's the license for the schema?

**Comment by rsperlazza** [comment]
It's open source from the same group that manages UML.

The license to the specification is here:
http://www.omg.org/spec/ReqIF/1.1/PDF/

**Comment by highsource** [comment]
Ok, so they won't sue me if I use it as a sample.

**Comment by rsperlazza** [comment]
Nope

**Comment by highsource** [comment]
I can't do thorough testing at the moment, but here's a trivial fix, hope it works.

**Comment by rsperlazza** [comment]
Made with maven, now we get this error:

Exception in thread "main" java.lang.NullPointerException
        at com.sun.tools.xjc.model.Multiplicity.multiply(Multiplicity.java:190)
        at org.hisrc.jsonix.xml.xsom.MultiplicityCounterNG.particle(Multiplicity
CounterNG.java:34)
        at org.hisrc.jsonix.xml.xsom.MultiplicityCounterNG.modelGroup(Multiplici
tyCounterNG.java:52)
        at org.hisrc.jsonix.xml.xsom.MultiplicityCounterNG.modelGroupDecl(Multip
licityCounterNG.java:43)
        at org.hisrc.jsonix.xml.xsom.MultiplicityCounterNG.modelGroupDecl(Multip
licityCounterNG.java:15)
        at com.sun.xml.xsom.impl.ModelGroupDeclImpl.apply(ModelGroupDeclImpl.jav
a:89)
        at org.hisrc.jsonix.xml.xsom.MultiplicityCounterNG.particle(Multiplicity
CounterNG.java:23)
        at org.hisrc.jsonix.xml.xsom.MultiplicityCounterNG.modelGroup(Multiplici
tyCounterNG.java:52)
        at org.hisrc.jsonix.xml.xsom.MultiplicityCounterNG.modelGroupDecl(Multip
licityCounterNG.java:43)
        at org.hisrc.jsonix.xml.xsom.MultiplicityCounterNG.modelGroupDecl(Multip
licityCounterNG.java:15)
        at com.sun.xml.xsom.impl.ModelGroupDeclImpl.apply(ModelGroupDeclImpl.jav
a:89)
        at org.hisrc.jsonix.xml.xsom.ParticleMultiplicityCounter.particle(Partic
leMultiplicityCounter.java:26)
        at org.hisrc.jsonix.xml.xsom.ParticleMultiplicityCounter.particle(Partic
leMultiplicityCounter.java:12)
        at com.sun.xml.xsom.impl.ParticleImpl.apply(ParticleImpl.java:111)
        at org.hisrc.xml.xsom.XSFunctionApplier.apply(XSFunctionApplier.java:26)

        at org.hisrc.jsonix.compilation.mapping.PropertyInfoVisitor.createProper
tyInfoOptions(PropertyInfoVisitor.java:59)
        at org.hisrc.jsonix.compilation.mapping.PropertyInfoVisitor.visitElement
RefsPropertyInfo(PropertyInfoVisitor.java:254)
        at org.hisrc.jsonix.compilation.mapping.PropertyInfoVisitor.visitElement
RefsPropertyInfo(PropertyInfoVisitor.java:38)
        at org.jvnet.jaxb2_commons.xml.bind.model.concrete.CMElementRefsProperty
Info.acceptPropertyInfoVisitor(CMElementRefsPropertyInfo.java:68)
        at org.hisrc.jsonix.compilation.mapping.MappingCompiler.compilePropertyI
nfos(MappingCompiler.java:262)
        at org.hisrc.jsonix.compilation.mapping.MappingCompiler.compileClassInfo
(MappingCompiler.java:232)
        at org.hisrc.jsonix.compilation.mapping.MappingCompiler.compileClassInfo
s(MappingCompiler.java:182)
        at org.hisrc.jsonix.compilation.mapping.MappingCompiler.compile(MappingC
ompiler.java:155)
        at org.hisrc.jsonix.compilation.mapping.ModuleCompiler.compile(ModuleCom
piler.java:54)
        at org.hisrc.jsonix.compilation.mapping.ModulesCompiler.compile(ModulesC
ompiler.java:29)
        at org.hisrc.jsonix.execution.JsonixInvoker.execute(JsonixInvoker.java:6
4)
        at org.hisrc.jsonix.JsonixMain.execute(JsonixMain.java:110)
        at org.hisrc.jsonix.JsonixMain.main(JsonixMain.java:77)

Any help would be appreciated.

**Comment by highsource** [comment]
Ok, good (or bad, actually). That was basically a blind shot, and I missed.

To address this, I'll have to make a reproducible test case to be able to debug it. I'm a bit "out of the normal life" at the moment, have a pretty bad internet connection. This means it will take me some time to create a reproducible test case.

You've a Maven build running - so If you want to give it a try on your own, try to fix NPEs. This whole multiplicity thing is just to determine min/max occurences for elements, it is pur metadata not used for unmarshalling or marshalling. So it is quite safe to return `null` for the cases when min/max occurs can't get reliably detected.

The NPEs which you get at the moment are programming errors.

**Comment by rsperlazza** [comment]
I added the null check and got another exception. When you get a chance, please create a reproducible test case and debug.

Thanks for all your help so far.

**Comment by chrisritter** [comment]
Any luck with ReqIF parsing in Jsonix?

**Comment by highsource** [comment]
Not yet, I did not come to this issue yet.

But don't worry, I'll get to it pretty soon.

**Comment by highsource** [comment]
This should be solved now. [This](https://github.com/highsource/jsonix-schema-compiler/blob/master/tests/reqif/src/main/resources/www.omg.org/spec/ReqIF/20110402/driver.xsd#L51-L53) was the offending part. Now fixed.

I've added [reqif](https://github.com/highsource/jsonix-support/tree/master/r/reqif) to [jsonix-support](https://github.com/highsource/jsonix-support).

To check this:

* Check out `jsonix-schema-compiler`.
* `mvn clean install`
* From `r/reqif` run `npm install ..../jsonix-schema-compiler-project/npm` to install the snapshot version
* `npm install`
* You should get `ReqIF_20110401.js` and `ReqIF_20110402_Driver.js` in `mappings`

Please let me know if it worked for you.

**Comment by chrisritter** [comment]
Thanks much -- Alexey -- I used the mappings JavaScript files in my test code and they worked!
